const sidebars = {
  deutschSidebar: [
    {
      type: 'category',
      label: 'A1 Niveau',
      collapsed: false, // Hiển thị mặc định các mục con
      items: [
        {
          type: 'category',
          label: 'Grammatik',
          items: [{ type: 'autogenerated', dirName: 'a1niveau/Grammatik' }],
        },
        {
          type: 'category',
          label: 'Hướng dẫn học tiếng Đức',
          items: [{ type: 'autogenerated', dirName: 'a1niveau/Hướng dẫn học tiếng Đức' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'A2 Niveau',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Grammatik',
          items: [{ type: 'autogenerated', dirName: 'a2niveau/Grammatik' }],
        },
        {
          type: 'category',
          label: 'Hướng dẫn học tiếng Đức',
          items: [{ type: 'autogenerated', dirName: 'a2niveau/Hướng dẫn học tiếng Đức' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'B1 Niveau',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Grammatik',
          items: [{ type: 'autogenerated', dirName: 'b1niveau/Grammatik' }],
        },
        {
          type: 'category',
          label: 'Hướng dẫn học tiếng Đức',
          items: [{ type: 'autogenerated', dirName: 'b1niveau/Hướng dẫn học tiếng Đức' }],
        },
        {
          type: 'category',
          label: 'Vokabular',
          items: [{ type: 'autogenerated', dirName: 'b1niveau/Vokabular' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'B2 Niveau',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Grammatik',
          items: [{ type: 'autogenerated', dirName: 'b2niveau/Grammatik' }],
        },
        {
          type: 'category',
          label: 'Hướng dẫn học tiếng Đức',
          items: [{ type: 'autogenerated', dirName: 'b2niveau/Hướng dẫn học tiếng Đức' }],
        },
      ],
    },
  ],
};

module.exports = sidebars;
