// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  a1niveau: [{ type: 'autogenerated', dirName: 'a1niveau' }],
  a2niveau: [{ type: 'autogenerated', dirName: 'a2niveau' }],
  b1niveau: [{ type: 'autogenerated', dirName: 'b1niveau' }],
  b2niveau: [{ type: 'autogenerated', dirName: 'b2niveau' }],

  // Sidebar cho "Bài Tập"
  baitap: [
    {
      type: 'category',
      label: 'Động từ bất quy tắc',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'link',
          label: 'Batch 1',
          href: '/demo/irregularverb/batch1', // Đường dẫn đến trang động
        },
        {
          type: 'link',
          label: 'Batch 2',
          href: '/demo/irregularverb/batch2',
        },
        {
          type: 'link',
          label: 'Batch 3',
          href: '/demo/irregularverb/batch3',
        },
        {
          type: 'link',
          label: 'Batch 4',
          href: '/demo/irregularverb/batch4',
        },
        {
          type: 'link',
          label: 'Batch 5',
          href: '/demo/irregularverb/batch5',
        },
        {
          type: 'link',
          label: 'Batch 6',
          href: '/demo/irregularverb/batch6',
        },
        {
          type: 'link',
          label: 'Batch 7',
          href: '/demo/irregularverb/batch7',
        },
        {
          type: 'link',
          label: 'Batch 8',
          href: '/demo/irregularverb/batch8',
        },
        {
          type: 'link',
          label: 'Batch 9',
          href: '/demo/irregularverb/batch9',
        },
        {
          type: 'link',
          label: 'Batch 10',
          href: '/demo/irregularverb/batch10',
        },
      ],
    },
    {
      type: 'category',
      label: 'Ngữ pháp A1',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'link',
          label: 'Bài 1',
          href: '/demo/ubungA1/grammatik/bai1',
        },
        {
          type: 'link',
          label: 'Bài 2',
          href: '/demo/ubungA1/grammatik/bai2',
        },
        {
          type: 'link',
          label: 'Bài 3',
          href: '/demo/ubungA1/grammatik/bai3',
        },
        {
          type: 'link',
          label: 'Bài 4',
          href: '/demo/ubungA1/grammatik/bai4',
        },
        {
          type: 'link',
          label: 'Bài 5',
          href: '/demo/ubungA1/grammatik/bai5',
        },
        {
          type: 'link',
          label: 'Bài 6',
          href: '/demo/ubungA1/grammatik/bai6',
        },
        {
          type: 'link',
          label: 'Bài 7',
          href: '/demo/ubungA1/grammatik/bai7',
        },
        {
          type: 'link',
          label: 'Bài 8',
          href: '/demo/ubungA1/grammatik/bai8',
        },
        {
          type: 'link',
          label: 'Bài 9',
          href: '/demo/ubungA1/grammatik/bai9',
        },
      ],
    },
  ],
};

module.exports = sidebars;
