// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  a1niveau: [{ type: 'autogenerated', dirName: 'a1niveau' }],
  a2niveau: [{ type: 'autogenerated', dirName: 'a2niveau' }],
  b1niveau: [{ type: 'autogenerated', dirName: 'b1niveau' }],
  b2niveau: [{ type: 'autogenerated', dirName: 'b2niveau' }],

  // Sidebar cho "Bài Tập"
  baitap: [
    {
      type: 'category',
      label: 'Động từ bất quy tắc',
      collapsible: true,
      collapsed: false,
      items: [
        'demo/irregularverb/batch1',
        'demo/irregularverb/batch2',
        'demo/irregularverb/batch3',
        'demo/irregularverb/batch4',
        'demo/irregularverb/batch5',
        'demo/irregularverb/batch6',
        'demo/irregularverb/batch7',
        'demo/irregularverb/batch8',
        'demo/irregularverb/batch9',
        'demo/irregularverb/batch10',
      ],
    },
    {
      type: 'category',
      label: 'Ngữ pháp A1',
      collapsible: true,
      collapsed: true,
      items: [
        'demo/ubungA1/grammatik/bai1',
        'demo/ubungA1/grammatik/bai2',
        'demo/ubungA1/grammatik/bai3',
        'demo/ubungA1/grammatik/bai4',
        'demo/ubungA1/grammatik/bai5',
        'demo/ubungA1/grammatik/bai6',
        'demo/ubungA1/grammatik/bai7',
        'demo/ubungA1/grammatik/bai8',
        'demo/ubungA1/grammatik/bai9',
      ],
    },
  ],
};

module.exports = sidebars;
